version: '3.3'
services:

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  app:
    build:
      context: ../app/
    restart: always
    volumes:
      - ../app/:/app
      - ../app/backend_static/:/home/app/backend_static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app/backend_static:/home/app/backend_static
    depends_on:
      - app
      
volumes:
  postgres_data:
  static_volume: