# Generated by Django 4.2.3 on 2023-07-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст вопроса', max_length=200, verbose_name='Текст вопроса')),
                ('is_correct', models.BooleanField(help_text='Правильность ответа', verbose_name='Правильность ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название теста', max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(help_text='Описание теста', verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='Дата обновления', verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=False, help_text='Если выбрана, прохождение доступно для пользователей. Должно быть как минимум 2 вопроса', verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ('-create_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст вопроса', max_length=200, verbose_name='Текст вопроса')),
                ('is_active', models.BooleanField(help_text='Включен в тест. В случае если активных вопросов в тесте станет меньше 2, тест автоматически снимется с публикации.', verbose_name='Включен в тест')),
                ('pool', models.ForeignKey(help_text='Вопрос теста', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Вариант ответа', max_length=50, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(help_text='Верный ли ответ', verbose_name='Верный ответ')),
                ('question', models.ForeignKey(help_text='Вариант ответа на вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название теста', max_length=100, verbose_name='Заголовок')),
                ('question_amount', models.IntegerField(help_text='Общее количество вопросов', verbose_name='Общее количество вопросов')),
                ('correct_answers_amount', models.IntegerField(help_text='Количество правильных ответов', verbose_name='Количество правильных ответов')),
                ('date_completed', models.DateTimeField(auto_now_add=True, help_text='Дата завершения', verbose_name='Дата завершения')),
                ('attempt', models.IntegerField(help_text='Номер попытки', verbose_name='Номер попытки')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.poll')),
                ('user', models.ForeignKey(help_text='Прошедший тест', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Прошедший тест')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChosenOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Вариант ответа', max_length=50, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(help_text='Верный ли ответ', verbose_name='Верный ответ')),
                ('is_chosen', models.BooleanField(help_text='Выбранный вариант', verbose_name='Выбранный вариант')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.option')),
                ('question', models.ForeignKey(help_text='Вариант ответа на вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.answeredquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.question'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='pool',
            field=models.ForeignKey(help_text='Вопрос теста', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.completedpool', verbose_name='Тест'),
        ),
    ]
